---
common:
  env: staging
  backups:
    destination: vientos@floriberto.mayfirst.org:tmp

website:
  name: website
  domain: staging.vientos.coop
  alternative_domain: www.staging.vientos.coop

app:
  name: app
  domain: app.staging.vientos.coop

service:
  name: service
  domain: data.staging.vientos.coop
  port: 8000

idp:
  name: idp
  domain: idp.staging.vientos.coop
  port: 8001

webhooks:
  name: webhooks
  domain: webhooks.staging.vientos.coop
  port: 8002